const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = 'https://fzqfcehkhyldkfmcizux.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cWZjZWhraHlsZGtmbWNpenV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzMTkwNDEsImV4cCI6MjA0ODg5NTA0MX0.Sg0mG6xB4Mz2-4P_6DgB6bDSrWZuGh0_nEy7XVx9r6c';
const supabase = createClient(supabaseUrl, supabaseKey);

const promotions = [
  {
    title: 'Taglio Capelli Uomo -30%',
    slug: 'taglio-capelli-uomo-sconto',
    description: 'Approfitta dello sconto del 30% sul taglio capelli uomo. Include shampoo e styling. Salone con prodotti professionali.',
    short_description: 'Taglio capelli -30%',
    partner_name: 'Salone Marco Hair',
    partner_address: 'Via Verdi 45',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20121',
    partner_phone: '+39 02 9876543',
    partner_email: 'info@marcohair.it',
    category: 'benessere',
    tags: ['parrucchiere', 'bellezza', 'uomo', 'taglio'],
    image_main: 'https://images.unsplash.com/photo-1622296089863-eb7fc530daa8',
    image_thumbnail: 'https://images.unsplash.com/photo-1622296089863-eb7fc530daa8?w=400',
    discount_type: 'percentage',
    discount_value: 30,
    original_price: 25.00,
    discounted_price: 17.50,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    validity_hours_from: '09:00',
    validity_hours_to: '19:00',
    limit_per_user: 2,
    is_active: true,
    is_featured: false,
    points_reward: 30,
    terms: 'Su prenotazione. Non valido nei weekend.',
    how_to_redeem: 'Mostra il QR code in cassa prima del servizio.'
  },
  {
    title: 'Lezione di Yoga Gratuita',
    slug: 'lezione-yoga-gratuita',
    description: 'Prima lezione di Yoga completamente gratuita. Scopri i benefici dello yoga con i nostri istruttori certificati. Include tappetino.',
    short_description: 'Prova Yoga Gratis',
    partner_name: 'Yoga Studio Milano',
    partner_address: 'Via Dante 78',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20123',
    partner_phone: '+39 02 5551234',
    partner_email: 'info@yogastudio.it',
    category: 'benessere',
    tags: ['yoga', 'fitness', 'salute', 'relax'],
    image_main: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b',
    image_thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    discount_type: 'fixed',
    discount_value: 15.00,
    original_price: 15.00,
    discounted_price: 0.00,
    validity_days: ['lun', 'mer', 'ven'],
    validity_hours_from: '18:00',
    validity_hours_to: '20:00',
    limit_per_user: 1,
    is_active: true,
    is_featured: true,
    points_reward: 80,
    terms: 'Solo per nuovi iscritti. Prenotazione obbligatoria.',
    how_to_redeem: 'Prenota online e mostra il QR code alla reception.'
  },
  {
    title: 'Lavaggio Auto Completo -40%',
    slug: 'lavaggio-auto-completo',
    description: 'Lavaggio esterno e interno completo con aspirazione e lucidatura. Include prodotti professionali e asciugatura.',
    short_description: 'Auto pulita -40%',
    partner_name: 'AutoClean Express',
    partner_address: 'Via Tibaldi 12',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20136',
    partner_phone: '+39 02 4445566',
    partner_email: 'info@autoclean.it',
    category: 'servizi',
    tags: ['auto', 'lavaggio', 'pulizia', 'manutenzione'],
    image_main: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9',
    image_thumbnail: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=400',
    discount_type: 'percentage',
    discount_value: 40,
    original_price: 30.00,
    discounted_price: 18.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '08:00',
    validity_hours_to: '20:00',
    limit_per_user: 3,
    is_active: true,
    is_featured: false,
    points_reward: 40,
    terms: 'Valido per auto di piccola e media cilindrata.',
    how_to_redeem: 'Mostra il QR code in cassa prima del servizio.'
  },
  {
    title: 'Colazione Completa €3.50',
    slug: 'colazione-completa-bar',
    description: 'Colazione italiana con brioche, caffè e succo di frutta. Ingredienti freschi ogni mattina. Ampia scelta di brioche.',
    short_description: 'Colazione a €3.50',
    partner_name: 'Bar Centrale',
    partner_address: 'Piazza Duomo 5',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20122',
    partner_phone: '+39 02 7778899',
    partner_email: 'info@barcentrale.it',
    category: 'ristoranti',
    tags: ['colazione', 'bar', 'caffè', 'brioche'],
    image_main: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085',
    image_thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    discount_type: 'fixed',
    discount_value: 2.00,
    original_price: 5.50,
    discounted_price: 3.50,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '07:00',
    validity_hours_to: '11:00',
    limit_per_user: 5,
    is_active: true,
    is_featured: true,
    points_reward: 20,
    terms: 'Valido solo al banco. Non cumulabile.',
    how_to_redeem: 'Mostra il QR code al barista prima di ordinare.'
  },
  {
    title: '2x1 Biglietto Cinema',
    slug: '2x1-biglietto-cinema',
    description: 'Prendi 2 biglietti e paghi 1! Valido per tutti i film in programmazione dal lunedì al giovedì. Sala con tecnologia Dolby Atmos.',
    short_description: '2 biglietti al prezzo di 1',
    partner_name: 'Multisala Odeon',
    partner_address: 'Corso Buenos Aires 23',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20124',
    partner_phone: '+39 02 3334455',
    partner_email: 'info@odeoncinema.it',
    category: 'intrattenimento',
    tags: ['cinema', 'film', 'spettacolo', '2x1'],
    image_main: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba',
    image_thumbnail: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
    discount_type: 'percentage',
    discount_value: 50,
    original_price: 20.00,
    discounted_price: 10.00,
    validity_days: ['lun', 'mar', 'mer', 'gio'],
    validity_hours_from: '14:00',
    validity_hours_to: '22:00',
    limit_per_user: 2,
    is_active: true,
    is_featured: true,
    points_reward: 60,
    terms: 'Non valido per anteprime e eventi speciali.',
    how_to_redeem: 'Acquista i biglietti online o in cassa mostrando il QR code.'
  },
  {
    title: '3 Libri paghi 2',
    slug: 'tre-libri-paghi-due',
    description: 'Acquista 3 libri e paghi solo 2! Il libro di minor valore è gratis. Valido su tutto il catalogo disponibile in negozio.',
    short_description: '3x2 sui libri',
    partner_name: 'Libreria Mondadori',
    partner_address: 'Via Manzoni 1',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20121',
    partner_phone: '+39 02 6667788',
    partner_email: 'info@mondadorilibri.it',
    category: 'servizi',
    tags: ['libri', 'lettura', 'cultura', 'sconto'],
    image_main: 'https://images.unsplash.com/photo-1512820790803-83ca734da794',
    image_thumbnail: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    discount_type: 'percentage',
    discount_value: 33,
    original_price: 45.00,
    discounted_price: 30.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    validity_hours_from: '09:00',
    validity_hours_to: '19:30',
    limit_per_user: 1,
    is_active: true,
    is_featured: false,
    points_reward: 70,
    terms: 'Esclusi libri scolastici e scontistica già applicata.',
    how_to_redeem: 'Mostra il QR code in cassa al momento del pagamento.'
  },
  {
    title: 'Hamburger + Patatine + Bibita €8',
    slug: 'hamburger-menu-completo',
    description: 'Menu completo con hamburger 200g di carne chianina, patatine fritte e bibita a scelta. Ingredienti freschi e di qualità.',
    short_description: 'Menu Burger €8',
    partner_name: 'Burger House',
    partner_address: 'Corso di Porta Ticinese 80',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20123',
    partner_phone: '+39 02 5556677',
    partner_email: 'info@burgerhouse.it',
    category: 'ristoranti',
    tags: ['hamburger', 'fast food', 'americano', 'menu'],
    image_main: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    image_thumbnail: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    discount_type: 'fixed',
    discount_value: 6.00,
    original_price: 14.00,
    discounted_price: 8.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '12:00',
    validity_hours_to: '23:00',
    limit_per_user: 4,
    is_active: true,
    is_featured: true,
    points_reward: 50,
    terms: 'Solo consumazione al tavolo. Escluso asporto.',
    how_to_redeem: 'Mostra il QR code al cameriere prima di ordinare.'
  },
  {
    title: 'Massaggio Rilassante 50min -35%',
    slug: 'massaggio-rilassante-sconto',
    description: 'Massaggio rilassante di 50 minuti con oli essenziali. Ambiente tranquillo e operatori qualificati. Include tisana post-trattamento.',
    short_description: 'Massaggio -35%',
    partner_name: 'Zen Spa Milano',
    partner_address: 'Via Montenapoleone 8',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20121',
    partner_phone: '+39 02 8889900',
    partner_email: 'info@zenspa.it',
    category: 'benessere',
    tags: ['massaggio', 'relax', 'spa', 'benessere'],
    image_main: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874',
    image_thumbnail: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    discount_type: 'percentage',
    discount_value: 35,
    original_price: 70.00,
    discounted_price: 45.50,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    validity_hours_from: '10:00',
    validity_hours_to: '20:00',
    limit_per_user: 2,
    is_active: true,
    is_featured: true,
    points_reward: 90,
    terms: 'Prenotazione obbligatoria. Cancellazione fino a 24h prima.',
    how_to_redeem: 'Prenota telefonicamente e mostra il QR code alla reception.'
  },
  {
    title: '-20% su Abbigliamento Sportivo',
    slug: 'sconto-abbigliamento-sportivo',
    description: 'Sconto del 20% su tutto l\'abbigliamento sportivo. Marchi Nike, Adidas, Puma e altri. Valido su prodotti non già scontati.',
    short_description: 'Sportswear -20%',
    partner_name: 'Sport Store Milano',
    partner_address: 'Corso Vercelli 50',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20144',
    partner_phone: '+39 02 4443322',
    partner_email: 'info@sportstore.it',
    category: 'shopping',
    tags: ['sport', 'abbigliamento', 'fitness', 'scarpe'],
    image_main: 'https://images.unsplash.com/photo-1556906781-9a412961c28c',
    image_thumbnail: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400',
    discount_type: 'percentage',
    discount_value: 20,
    original_price: 100.00,
    discounted_price: 80.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    validity_hours_from: '09:30',
    validity_hours_to: '19:30',
    limit_per_user: 3,
    is_active: true,
    is_featured: false,
    points_reward: 60,
    terms: 'Non valido su articoli già in promozione.',
    how_to_redeem: 'Mostra il QR code in cassa prima del pagamento.'
  },
  {
    title: 'All You Can Eat Sushi €19.90',
    slug: 'all-you-can-eat-sushi',
    description: 'Formula All You Can Eat a pranzo e cena. Menu completo con sushi, sashimi, uramaki e piatti caldi. Pesce fresco ogni giorno.',
    short_description: 'Sushi illimitato €19.90',
    partner_name: 'Sakura Sushi Restaurant',
    partner_address: 'Via Paolo Sarpi 15',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20154',
    partner_phone: '+39 02 3338844',
    partner_email: 'info@sakurasushi.it',
    category: 'ristoranti',
    tags: ['sushi', 'giapponese', 'all you can eat', 'pesce'],
    image_main: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351',
    image_thumbnail: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
    discount_type: 'fixed',
    discount_value: 5.00,
    original_price: 24.90,
    discounted_price: 19.90,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '12:00',
    validity_hours_to: '15:00',
    limit_per_user: 2,
    is_active: true,
    is_featured: true,
    points_reward: 70,
    terms: 'Bevande escluse. Limite di tempo 2 ore.',
    how_to_redeem: 'Prenota e mostra il QR code all\'ingresso.'
  },
  {
    title: 'Prima Lezione di Chitarra Gratis',
    slug: 'lezione-chitarra-gratuita',
    description: 'Lezione di prova gratuita di chitarra classica o elettrica. Insegnanti diplomati al conservatorio. Include materiale didattico.',
    short_description: 'Lezione Chitarra Gratis',
    partner_name: 'Music Academy Milano',
    partner_address: 'Via Boccaccio 70',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20123',
    partner_phone: '+39 02 7774455',
    partner_email: 'info@musicacademy.it',
    category: 'servizi',
    tags: ['musica', 'chitarra', 'corso', 'lezione'],
    image_main: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1',
    image_thumbnail: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400',
    discount_type: 'fixed',
    discount_value: 30.00,
    original_price: 30.00,
    discounted_price: 0.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven'],
    validity_hours_from: '14:00',
    validity_hours_to: '20:00',
    limit_per_user: 1,
    is_active: true,
    is_featured: false,
    points_reward: 85,
    terms: 'Solo per nuovi studenti. Prenotazione obbligatoria.',
    how_to_redeem: 'Prenota telefonicamente e mostra il QR code alla reception.'
  },
  {
    title: 'Aperitivo con Buffet €7',
    slug: 'aperitivo-buffet-sette-euro',
    description: 'Aperitivo con drink a scelta e accesso al buffet ricco. Spritz, cocktail classici o analcolici. Terrazza panoramica disponibile.',
    short_description: 'Aperitivo + Buffet €7',
    partner_name: 'Lounge Bar Navigli',
    partner_address: 'Alzaia Naviglio Grande 44',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20144',
    partner_phone: '+39 02 5552233',
    partner_email: 'info@loungenaviglia.it',
    category: 'ristoranti',
    tags: ['aperitivo', 'cocktail', 'buffet', 'happy hour'],
    image_main: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b',
    image_thumbnail: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400',
    discount_type: 'fixed',
    discount_value: 5.00,
    original_price: 12.00,
    discounted_price: 7.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '18:00',
    validity_hours_to: '21:00',
    limit_per_user: 3,
    is_active: true,
    is_featured: true,
    points_reward: 45,
    terms: 'Consumazione al tavolo. Prenotazione consigliata nel weekend.',
    how_to_redeem: 'Mostra il QR code al cameriere prima di ordinare.'
  },
  {
    title: 'Scarpe Running -25%',
    slug: 'scarpe-running-sconto',
    description: 'Sconto del 25% su tutte le scarpe da running. Modelli Nike, Asics, New Balance. Analisi del passo gratuita in negozio.',
    short_description: 'Running Shoes -25%',
    partner_name: 'Runner\'s World',
    partner_address: 'Via Washington 70',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20146',
    partner_phone: '+39 02 6665544',
    partner_email: 'info@runnersworld.it',
    category: 'shopping',
    tags: ['scarpe', 'running', 'sport', 'corsa'],
    image_main: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    image_thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    discount_type: 'percentage',
    discount_value: 25,
    original_price: 120.00,
    discounted_price: 90.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    validity_hours_from: '09:00',
    validity_hours_to: '19:30',
    limit_per_user: 1,
    is_active: true,
    is_featured: false,
    points_reward: 75,
    terms: 'Solo prodotti selezionati. Soggetto a disponibilità.',
    how_to_redeem: 'Mostra il QR code in cassa al momento dell\'acquisto.'
  },
  {
    title: 'Pizza Gourmet + Dolce €12',
    slug: 'pizza-gourmet-con-dolce',
    description: 'Pizza gourmet a scelta dal menu speciale più dolce della casa. Ingredienti DOP e lievitazione naturale 48h. Birra artigianale disponibile.',
    short_description: 'Pizza Gourmet + Dolce',
    partner_name: 'Pizzeria Stella',
    partner_address: 'Via Tortona 31',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20144',
    partner_phone: '+39 02 4446677',
    partner_email: 'info@pizzeriastella.it',
    category: 'ristoranti',
    tags: ['pizza', 'gourmet', 'italiano', 'ristorante'],
    image_main: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002',
    image_thumbnail: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    discount_type: 'fixed',
    discount_value: 6.00,
    original_price: 18.00,
    discounted_price: 12.00,
    validity_days: ['mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '19:00',
    validity_hours_to: '23:30',
    limit_per_user: 2,
    is_active: true,
    is_featured: true,
    points_reward: 65,
    terms: 'Valido solo a cena. Prenotazione consigliata.',
    how_to_redeem: 'Mostra il QR code al cameriere prima di ordinare.'
  },
  {
    title: 'Corso Photoshop Base -40%',
    slug: 'corso-photoshop-base-sconto',
    description: 'Corso base di Adobe Photoshop di 12 ore. Include certificato finale e materiale didattico. Docenti certificati Adobe.',
    short_description: 'Photoshop Base -40%',
    partner_name: 'Digital School Milano',
    partner_address: 'Via Mecenate 84',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20138',
    partner_phone: '+39 02 9998877',
    partner_email: 'info@digitalschool.it',
    category: 'servizi',
    tags: ['corso', 'photoshop', 'grafica', 'formazione'],
    image_main: 'https://images.unsplash.com/photo-1626785774573-4b799315345d',
    image_thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400',
    discount_type: 'percentage',
    discount_value: 40,
    original_price: 300.00,
    discounted_price: 180.00,
    validity_days: ['lun', 'mer', 'ven'],
    validity_hours_from: '18:30',
    validity_hours_to: '21:30',
    limit_per_user: 1,
    is_active: true,
    is_featured: false,
    points_reward: 120,
    terms: 'Iscrizione anticipata. Minimo 5 partecipanti.',
    how_to_redeem: 'Iscriviti online e mostra il QR code il primo giorno.'
  },
  {
    title: 'Coppetta 3 Gusti €3',
    slug: 'coppetta-gelato-tre-gusti',
    description: 'Coppetta con 3 gusti a scelta tra oltre 30 sapori. Gelato artigianale fatto con ingredienti naturali. Include panna montata.',
    short_description: 'Gelato 3 gusti €3',
    partner_name: 'Gelateria Giolitti',
    partner_address: 'Corso di Porta Romana 96',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20122',
    partner_phone: '+39 02 3337766',
    partner_email: 'info@giolitti.it',
    category: 'ristoranti',
    tags: ['gelato', 'dolce', 'artigianale', 'dessert'],
    image_main: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb',
    image_thumbnail: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    discount_type: 'fixed',
    discount_value: 1.50,
    original_price: 4.50,
    discounted_price: 3.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '12:00',
    validity_hours_to: '23:00',
    limit_per_user: 5,
    is_active: true,
    is_featured: true,
    points_reward: 25,
    terms: 'Solo consumazione in negozio o asporto.',
    how_to_redeem: 'Mostra il QR code in cassa prima di ordinare.'
  },
  {
    title: 'Ingresso Piscina €6',
    slug: 'ingresso-piscina-sconto',
    description: 'Ingresso giornaliero alla piscina olimpionica. Include utilizzo spogliatoi e docce. Lettini e ombrelloni disponibili.',
    short_description: 'Piscina €6',
    partner_name: 'Piscina Cozzi',
    partner_address: 'Viale Tunisia 35',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20124',
    partner_phone: '+39 02 7776655',
    partner_email: 'info@piscinacozzi.it',
    category: 'benessere',
    tags: ['piscina', 'nuoto', 'sport', 'relax'],
    image_main: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7',
    image_thumbnail: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=400',
    discount_type: 'fixed',
    discount_value: 4.00,
    original_price: 10.00,
    discounted_price: 6.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '07:00',
    validity_hours_to: '21:00',
    limit_per_user: 4,
    is_active: true,
    is_featured: false,
    points_reward: 40,
    terms: 'Portare costume e cuffia. Certificato medico richiesto.',
    how_to_redeem: 'Mostra il QR code alla reception.'
  },
  {
    title: '3 Tacos + Nachos €9',
    slug: 'tre-tacos-con-nachos',
    description: 'Menu con 3 tacos a scelta (carne, pollo o vegano) più porzione di nachos con guacamole e salsa. Cucina messicana autentica.',
    short_description: '3 Tacos + Nachos €9',
    partner_name: 'El Sombrero Loco',
    partner_address: 'Via Vigevano 18',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20144',
    partner_phone: '+39 02 4445533',
    partner_email: 'info@elsombrero.it',
    category: 'ristoranti',
    tags: ['messicano', 'tacos', 'etnico', 'street food'],
    image_main: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47',
    image_thumbnail: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    discount_type: 'fixed',
    discount_value: 4.00,
    original_price: 13.00,
    discounted_price: 9.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    validity_hours_from: '12:00',
    validity_hours_to: '23:00',
    limit_per_user: 3,
    is_active: true,
    is_featured: true,
    points_reward: 55,
    terms: 'Bevande escluse. Anche asporto disponibile.',
    how_to_redeem: 'Mostra il QR code prima di ordinare.'
  },
  {
    title: '5 Manga paghi 4',
    slug: 'cinque-manga-paghi-quattro',
    description: 'Acquista 5 volumi manga e paghi solo 4! Ampio catalogo con tutte le ultime uscite. Anche fumetti e graphic novel disponibili.',
    short_description: '5 Manga = 4 prezzi',
    partner_name: 'Fumetteria Panini Comics',
    partner_address: 'Via Torino 51',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20123',
    partner_phone: '+39 02 8887766',
    partner_email: 'info@paninicomics.it',
    category: 'shopping',
    tags: ['manga', 'fumetti', 'libri', 'giapponese'],
    image_main: 'https://images.unsplash.com/photo-1612178537253-bccd437b730e',
    image_thumbnail: 'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=400',
    discount_type: 'percentage',
    discount_value: 20,
    original_price: 30.00,
    discounted_price: 24.00,
    validity_days: ['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    validity_hours_from: '10:00',
    validity_hours_to: '19:30',
    limit_per_user: 2,
    is_active: true,
    is_featured: false,
    points_reward: 50,
    terms: 'Escluse edizioni limitate e preordini.',
    how_to_redeem: 'Mostra il QR code in cassa.'
  },
  {
    title: 'Brunch Domenicale €15',
    slug: 'brunch-domenicale-offerta',
    description: 'Brunch all-inclusive ogni domenica. Dolce, salato, bevande calde e cocktail. Atmosfera rilassante con musica dal vivo.',
    short_description: 'Brunch Domenica €15',
    partner_name: 'The Breakfast Club',
    partner_address: 'Via Solferino 25',
    partner_city: 'Milano',
    partner_province: 'MI',
    partner_zip_code: '20121',
    partner_phone: '+39 02 6664433',
    partner_email: 'info@breakfastclub.it',
    category: 'ristoranti',
    tags: ['brunch', 'colazione', 'domenica', 'buffet'],
    image_main: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    image_thumbnail: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    discount_type: 'fixed',
    discount_value: 10.00,
    original_price: 25.00,
    discounted_price: 15.00,
    validity_days: ['dom'],
    validity_hours_from: '10:00',
    validity_hours_to: '15:00',
    limit_per_user: 2,
    is_active: true,
    is_featured: true,
    points_reward: 80,
    terms: 'Solo la domenica. Prenotazione obbligatoria.',
    how_to_redeem: 'Prenota online e mostra il QR code all\'ingresso.'
  }
];

async function addPromotions() {
  try {
    console.log('🚀 Inizio aggiunta promozioni...\n');

    // Get any user ID (first one found)
    const { data: users, error: userError } = await supabase
      .from('users')
      .select('id, email')
      .limit(1);

    if (userError || !users || users.length === 0) {
      console.error('❌ Errore: nessun utente trovato nel database');
      console.log('Creo un utente temporaneo...');
      
      // Create a temporary admin user
      const { data: newUser, error: createError } = await supabase
        .from('users')
        .insert({
          email: 'admin@cdm86.com',
          name: 'Admin CDM86',
          phone: '+39 02 1234567',
          referral_code: 'ADMIN001'
        })
        .select()
        .single();
      
      if (createError || !newUser) {
        console.error('❌ Impossibile creare utente:', createError);
        process.exit(1);
      }
      
      const adminId = newUser.id;
      console.log('✅ Utente creato:', newUser.email, adminId, '\n');
    } else {
      const adminId = users[0].id;
      console.log('✅ Utente trovato:', users[0].email, adminId, '\n');
    }

    // Use the found or created user ID
    const { data: finalUser } = await supabase
      .from('users')
      .select('id')
      .limit(1)
      .single();
    
    const adminId = finalUser.id;

    // Add created_by_id and dates to all promotions
    const promotionsWithMeta = promotions.map(promo => ({
      ...promo,
      created_by_id: adminId,
      validity_start_date: new Date().toISOString(),
      validity_end_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString()
    }));

    // Insert promotions in batches
    const batchSize = 5;
    let successCount = 0;

    for (let i = 0; i < promotionsWithMeta.length; i += batchSize) {
      const batch = promotionsWithMeta.slice(i, i + batchSize);
      
      const { data, error } = await supabase
        .from('promotions')
        .insert(batch)
        .select();

      if (error) {
        console.error(`❌ Errore batch ${i / batchSize + 1}:`, error);
      } else {
        successCount += batch.length;
        console.log(`✅ Batch ${i / batchSize + 1} completato: ${batch.length} promozioni aggiunte`);
        batch.forEach(p => console.log(`   - ${p.title}`));
      }
    }

    console.log(`\n🎉 Completato! ${successCount} promozioni aggiunte con successo!\n`);

    // Verify total count
    const { count } = await supabase
      .from('promotions')
      .select('*', { count: 'exact', head: true });

    console.log(`📊 Totale promozioni nel database: ${count}`);
    
  } catch (error) {
    console.error('❌ Errore generale:', error);
  } finally {
    process.exit(0);
  }
}

addPromotions();
