-- ============================================
-- Aggiunta di 20 nuove promozioni per testare la paginazione
-- ============================================

-- Promozione 7: Taglio Capelli Scontato
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Taglio Capelli Uomo -30%',
    'taglio-capelli-uomo-sconto',
    'Approfitta dello sconto del 30% sul taglio capelli uomo. Include shampoo e styling. Salone con prodotti professionali.',
    'Taglio capelli -30%',
    'Salone Marco Hair',
    'Via Verdi 45',
    'Milano',
    'MI',
    '20121',
    '+39 02 9876543',
    'info@marcohair.it',
    'benessere',
    ARRAY['parrucchiere', 'bellezza', 'uomo', 'taglio'],
    'https://images.unsplash.com/photo-1622296089863-eb7fc530daa8',
    'https://images.unsplash.com/photo-1622296089863-eb7fc530daa8?w=400',
    'percentage',
    30,
    25.00,
    17.50,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '60 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    '09:00',
    '19:00',
    2,
    true,
    false,
    30,
    'Su prenotazione. Non valido nei weekend.',
    'Mostra il QR code in cassa prima del servizio.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    120,
    8,
    45,
    6
);

-- Promozione 8: Corso di Yoga
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Lezione di Yoga Gratuita',
    'lezione-yoga-gratuita',
    'Prima lezione di Yoga completamente gratuita. Scopri i benefici dello yoga con i nostri istruttori certificati. Include tappetino.',
    'Prova Yoga Gratis',
    'Yoga Studio Milano',
    'Via Dante 78',
    'Milano',
    'MI',
    '20123',
    '+39 02 5551234',
    'info@yogastudio.it',
    'benessere',
    ARRAY['yoga', 'fitness', 'salute', 'relax'],
    'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b',
    'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    'fixed',
    15.00,
    15.00,
    0.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '90 days',
    ARRAY['lun', 'mer', 'ven'],
    '18:00',
    '20:00',
    1,
    true,
    true,
    80,
    'Solo per nuovi iscritti. Prenotazione obbligatoria.',
    'Prenota online e mostra il QR code alla reception.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    310,
    25,
    120,
    15
);

-- Promozione 9: Lavaggio Auto
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Lavaggio Auto Completo -40%',
    'lavaggio-auto-completo',
    'Lavaggio esterno e interno completo con aspirazione e lucidatura. Include prodotti professionali e asciugatura.',
    'Auto pulita -40%',
    'AutoClean Express',
    'Via Tibaldi 12',
    'Milano',
    'MI',
    '20136',
    '+39 02 4445566',
    'info@autoclean.it',
    'servizi',
    ARRAY['auto', 'lavaggio', 'pulizia', 'manutenzione'],
    'https://images.unsplash.com/photo-1607860108855-64acf2078ed9',
    'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=400',
    'percentage',
    40,
    30.00,
    18.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '45 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '08:00',
    '20:00',
    3,
    true,
    false,
    40,
    'Valido per auto di piccola e media cilindrata.',
    'Mostra il QR code in cassa prima del servizio.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    180,
    12,
    67,
    8
);

-- Promozione 10: Colazione Bar
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Colazione Completa €3.50',
    'colazione-completa-bar',
    'Colazione italiana con brioche, caffè e succo di frutta. Ingredienti freschi ogni mattina. Ampia scelta di brioche.',
    'Colazione a €3.50',
    'Bar Centrale',
    'Piazza Duomo 5',
    'Milano',
    'MI',
    '20122',
    '+39 02 7778899',
    'info@barcentrale.it',
    'ristoranti',
    ARRAY['colazione', 'bar', 'caffè', 'brioche'],
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085',
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    'fixed',
    2.00,
    5.50,
    3.50,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '07:00',
    '11:00',
    5,
    true,
    true,
    20,
    'Valido solo al banco. Non cumulabile.',
    'Mostra il QR code al barista prima di ordinare.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    420,
    35,
    210,
    28
);

-- Promozione 11: Cinema 2x1
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    '2x1 Biglietto Cinema',
    '2x1-biglietto-cinema',
    'Prendi 2 biglietti e paghi 1! Valido per tutti i film in programmazione dal lunedì al giovedì. Sala con tecnologia Dolby Atmos.',
    '2 biglietti al prezzo di 1',
    'Multisala Odeon',
    'Corso Buenos Aires 23',
    'Milano',
    'MI',
    '20124',
    '+39 02 3334455',
    'info@odeoncinema.it',
    'intrattenimento',
    ARRAY['cinema', 'film', 'spettacolo', '2x1'],
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba',
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
    'percentage',
    50,
    20.00,
    10.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '60 days',
    ARRAY['lun', 'mar', 'mer', 'gio'],
    '14:00',
    '22:00',
    2,
    true,
    true,
    60,
    'Non valido per anteprime e eventi speciali.',
    'Acquista i biglietti online o in cassa mostrando il QR code.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    560,
    48,
    280,
    32
);

-- Promozione 12: Libro Gratis
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    '3 Libri paghi 2',
    'tre-libri-paghi-due',
    'Acquista 3 libri e paghi solo 2! Il libro di minor valore è gratis. Valido su tutto il catalogo disponibile in negozio.',
    '3x2 sui libri',
    'Libreria Mondadori',
    'Via Manzoni 1',
    'Milano',
    'MI',
    '20121',
    '+39 02 6667788',
    'info@mondadorilibri.it',
    'servizi',
    ARRAY['libri', 'lettura', 'cultura', 'sconto'],
    'https://images.unsplash.com/photo-1512820790803-83ca734da794',
    'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    'percentage',
    33,
    45.00,
    30.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '90 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    '09:00',
    '19:30',
    1,
    true,
    false,
    70,
    'Esclusi libri scolastici e scontistica già applicata.',
    'Mostra il QR code in cassa al momento del pagamento.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    290,
    22,
    145,
    18
);

-- Promozione 13: Hamburger Gourmet
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Hamburger + Patatine + Bibita €8',
    'hamburger-menu-completo',
    'Menu completo con hamburger 200g di carne chianina, patatine fritte e bibita a scelta. Ingredienti freschi e di qualità.',
    'Menu Burger €8',
    'Burger House',
    'Corso di Porta Ticinese 80',
    'Milano',
    'MI',
    '20123',
    '+39 02 5556677',
    'info@burgerhouse.it',
    'ristoranti',
    ARRAY['hamburger', 'fast food', 'americano', 'menu'],
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    'fixed',
    6.00,
    14.00,
    8.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '12:00',
    '23:00',
    4,
    true,
    true,
    50,
    'Solo consumazione al tavolo. Escluso asporto.',
    'Mostra il QR code al cameriere prima di ordinare.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    380,
    30,
    190,
    22
);

-- Promozione 14: Massaggio Relax
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Massaggio Rilassante 50min -35%',
    'massaggio-rilassante-sconto',
    'Massaggio rilassante di 50 minuti con oli essenziali. Ambiente tranquillo e operatori qualificati. Include tisana post-trattamento.',
    'Massaggio -35%',
    'Zen Spa Milano',
    'Via Montenapoleone 8',
    'Milano',
    'MI',
    '20121',
    '+39 02 8889900',
    'info@zenspa.it',
    'benessere',
    ARRAY['massaggio', 'relax', 'spa', 'benessere'],
    'https://images.unsplash.com/photo-1544161515-4ab6ce6db874',
    'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    'percentage',
    35,
    70.00,
    45.50,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '60 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    '10:00',
    '20:00',
    2,
    true,
    true,
    90,
    'Prenotazione obbligatoria. Cancellazione fino a 24h prima.',
    'Prenota telefonicamente e mostra il QR code alla reception.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    220,
    18,
    95,
    12
);

-- Promozione 15: Abbigliamento Sportivo
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    '-20% su Abbigliamento Sportivo',
    'sconto-abbigliamento-sportivo',
    'Sconto del 20% su tutto l\'abbigliamento sportivo. Marchi Nike, Adidas, Puma e altri. Valido su prodotti non già scontati.',
    'Sportswear -20%',
    'Sport Store Milano',
    'Corso Vercelli 50',
    'Milano',
    'MI',
    '20144',
    '+39 02 4443322',
    'info@sportstore.it',
    'shopping',
    ARRAY['sport', 'abbigliamento', 'fitness', 'scarpe'],
    'https://images.unsplash.com/photo-1556906781-9a412961c28c',
    'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400',
    'percentage',
    20,
    100.00,
    80.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '45 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    '09:30',
    '19:30',
    3,
    true,
    false,
    60,
    'Non valido su articoli già in promozione.',
    'Mostra il QR code in cassa prima del pagamento.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    340,
    28,
    170,
    20
);

-- Promozione 16: Sushi All You Can Eat
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'All You Can Eat Sushi €19.90',
    'all-you-can-eat-sushi',
    'Formula All You Can Eat a pranzo e cena. Menu completo con sushi, sashimi, uramaki e piatti caldi. Pesce fresco ogni giorno.',
    'Sushi illimitato €19.90',
    'Sakura Sushi Restaurant',
    'Via Paolo Sarpi 15',
    'Milano',
    'MI',
    '20154',
    '+39 02 3338844',
    'info@sakurasushi.it',
    'ristoranti',
    ARRAY['sushi', 'giapponese', 'all you can eat', 'pesce'],
    'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351',
    'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
    'fixed',
    5.00,
    24.90,
    19.90,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '12:00',
    '15:00',
    2,
    true,
    true,
    70,
    'Bevande escluse. Limite di tempo 2 ore.',
    'Prenota e mostra il QR code all\'ingresso.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    680,
    55,
    340,
    45
);

-- Promozione 17: Lezione di Chitarra
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Prima Lezione di Chitarra Gratis',
    'lezione-chitarra-gratuita',
    'Lezione di prova gratuita di chitarra classica o elettrica. Insegnanti diplomati al conservatorio. Include materiale didattico.',
    'Lezione Chitarra Gratis',
    'Music Academy Milano',
    'Via Boccaccio 70',
    'Milano',
    'MI',
    '20123',
    '+39 02 7774455',
    'info@musicacademy.it',
    'servizi',
    ARRAY['musica', 'chitarra', 'corso', 'lezione'],
    'https://images.unsplash.com/photo-1510915361894-db8b60106cb1',
    'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400',
    'fixed',
    30.00,
    30.00,
    0.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '90 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven'],
    '14:00',
    '20:00',
    1,
    true,
    false,
    85,
    'Solo per nuovi studenti. Prenotazione obbligatoria.',
    'Prenota telefonicamente e mostra il QR code alla reception.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    150,
    12,
    68,
    8
);

-- Promozione 18: Aperitivo
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Aperitivo con Buffet €7',
    'aperitivo-buffet-sette-euro',
    'Aperitivo con drink a scelta e accesso al buffet ricco. Spritz, cocktail classici o analcolici. Terrazza panoramica disponibile.',
    'Aperitivo + Buffet €7',
    'Lounge Bar Navigli',
    'Alzaia Naviglio Grande 44',
    'Milano',
    'MI',
    '20144',
    '+39 02 5552233',
    'info@loungenaviglia.it',
    'ristoranti',
    ARRAY['aperitivo', 'cocktail', 'buffet', 'happy hour'],
    'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b',
    'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400',
    'fixed',
    5.00,
    12.00,
    7.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '18:00',
    '21:00',
    3,
    true,
    true,
    45,
    'Consumazione al tavolo. Prenotazione consigliata nel weekend.',
    'Mostra il QR code al cameriere prima di ordinare.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    520,
    42,
    260,
    35
);

-- Promozione 19: Scarpe Running
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Scarpe Running -25%',
    'scarpe-running-sconto',
    'Sconto del 25% su tutte le scarpe da running. Modelli Nike, Asics, New Balance. Analisi del passo gratuita in negozio.',
    'Running Shoes -25%',
    'Runner\'s World',
    'Via Washington 70',
    'Milano',
    'MI',
    '20146',
    '+39 02 6665544',
    'info@runnersworld.it',
    'shopping',
    ARRAY['scarpe', 'running', 'sport', 'corsa'],
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    'percentage',
    25,
    120.00,
    90.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '60 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    '09:00',
    '19:30',
    1,
    true,
    false,
    75,
    'Solo prodotti selezionati. Soggetto a disponibilità.',
    'Mostra il QR code in cassa al momento dell\'acquisto.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    280,
    24,
    140,
    16
);

-- Promozione 20: Pizza Gourmet
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Pizza Gourmet + Dolce €12',
    'pizza-gourmet-con-dolce',
    'Pizza gourmet a scelta dal menu speciale più dolce della casa. Ingredienti DOP e lievitazione naturale 48h. Birra artigianale disponibile.',
    'Pizza Gourmet + Dolce',
    'Pizzeria Stella',
    'Via Tortona 31',
    'Milano',
    'MI',
    '20144',
    '+39 02 4446677',
    'info@pizzeriastella.it',
    'ristoranti',
    ARRAY['pizza', 'gourmet', 'italiano', 'ristorante'],
    'https://images.unsplash.com/photo-1574071318508-1cdbab80d002',
    'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    'fixed',
    6.00,
    18.00,
    12.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '19:00',
    '23:30',
    2,
    true,
    true,
    65,
    'Valido solo a cena. Prenotazione consigliata.',
    'Mostra il QR code al cameriere prima di ordinare.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    410,
    33,
    205,
    26
);

-- Promozione 21: Corso Photoshop
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Corso Photoshop Base -40%',
    'corso-photoshop-base-sconto',
    'Corso base di Adobe Photoshop di 12 ore. Include certificato finale e materiale didattico. Docenti certificati Adobe.',
    'Photoshop Base -40%',
    'Digital School Milano',
    'Via Mecenate 84',
    'Milano',
    'MI',
    '20138',
    '+39 02 9998877',
    'info@digitalschool.it',
    'servizi',
    ARRAY['corso', 'photoshop', 'grafica', 'formazione'],
    'https://images.unsplash.com/photo-1626785774573-4b799315345d',
    'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400',
    'percentage',
    40,
    300.00,
    180.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '90 days',
    ARRAY['lun', 'mer', 'ven'],
    '18:30',
    '21:30',
    1,
    true,
    false,
    120,
    'Iscrizione anticipata. Minimo 5 partecipanti.',
    'Iscriviti online e mostra il QR code il primo giorno.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    190,
    15,
    85,
    9
);

-- Promozione 22: Gelato Artigianale
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Coppetta 3 Gusti €3',
    'coppetta-gelato-tre-gusti',
    'Coppetta con 3 gusti a scelta tra oltre 30 sapori. Gelato artigianale fatto con ingredienti naturali. Include panna montata.',
    'Gelato 3 gusti €3',
    'Gelateria Giolitti',
    'Corso di Porta Romana 96',
    'Milano',
    'MI',
    '20122',
    '+39 02 3337766',
    'info@giolitti.it',
    'ristoranti',
    ARRAY['gelato', 'dolce', 'artigianale', 'dessert'],
    'https://images.unsplash.com/photo-1563805042-7684c019e1cb',
    'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    'fixed',
    1.50,
    4.50,
    3.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '12:00',
    '23:00',
    5,
    true,
    true,
    25,
    'Solo consumazione in negozio o asporto.',
    'Mostra il QR code in cassa prima di ordinare.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    630,
    51,
    315,
    42
);

-- Promozione 23: Piscina Ingresso
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Ingresso Piscina €6',
    'ingresso-piscina-sconto',
    'Ingresso giornaliero alla piscina olimpionica. Include utilizzo spogliatoi e docce. Lettini e ombrelloni disponibili.',
    'Piscina €6',
    'Piscina Cozzi',
    'Viale Tunisia 35',
    'Milano',
    'MI',
    '20124',
    '+39 02 7776655',
    'info@piscinacozzi.it',
    'benessere',
    ARRAY['piscina', 'nuoto', 'sport', 'relax'],
    'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7',
    'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=400',
    'fixed',
    4.00,
    10.00,
    6.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '60 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '07:00',
    '21:00',
    4,
    true,
    false,
    40,
    'Portare costume e cuffia. Certificato medico richiesto.',
    'Mostra il QR code alla reception.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    270,
    21,
    135,
    18
);

-- Promozione 24: Tacos Messicano
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    '3 Tacos + Nachos €9',
    'tre-tacos-con-nachos',
    'Menu con 3 tacos a scelta (carne, pollo o vegano) più porzione di nachos con guacamole e salsa. Cucina messicana autentica.',
    '3 Tacos + Nachos €9',
    'El Sombrero Loco',
    'Via Vigevano 18',
    'Milano',
    'MI',
    '20144',
    '+39 02 4445533',
    'info@elsombrero.it',
    'ristoranti',
    ARRAY['messicano', 'tacos', 'etnico', 'street food'],
    'https://images.unsplash.com/photo-1565299585323-38d6b0865b47',
    'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    'fixed',
    4.00,
    13.00,
    9.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom'],
    '12:00',
    '23:00',
    3,
    true,
    true,
    55,
    'Bevande escluse. Anche asporto disponibile.',
    'Mostra il QR code prima di ordinare.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    390,
    32,
    195,
    24
);

-- Promozione 25: Fumetti Manga
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    '5 Manga paghi 4',
    'cinque-manga-paghi-quattro',
    'Acquista 5 volumi manga e paghi solo 4! Ampio catalogo con tutte le ultime uscite. Anche fumetti e graphic novel disponibili.',
    '5 Manga = 4 prezzi',
    'Fumetteria Panini Comics',
    'Via Torino 51',
    'Milano',
    'MI',
    '20123',
    '+39 02 8887766',
    'info@paninicomics.it',
    'shopping',
    ARRAY['manga', 'fumetti', 'libri', 'giapponese'],
    'https://images.unsplash.com/photo-1612178537253-bccd437b730e',
    'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=400',
    'percentage',
    20,
    30.00,
    24.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '60 days',
    ARRAY['lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    '10:00',
    '19:30',
    2,
    true,
    false,
    50,
    'Escluse edizioni limitate e preordini.',
    'Mostra il QR code in cassa.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    240,
    20,
    120,
    14
);

-- Promozione 26: Brunch Domenicale
INSERT INTO promotions (
    title,
    slug,
    description,
    short_description,
    partner_name,
    partner_address,
    partner_city,
    partner_province,
    partner_zip_code,
    partner_phone,
    partner_email,
    category,
    tags,
    image_main,
    image_thumbnail,
    discount_type,
    discount_value,
    original_price,
    discounted_price,
    validity_start_date,
    validity_end_date,
    validity_days,
    validity_hours_from,
    validity_hours_to,
    limit_per_user,
    is_active,
    is_featured,
    points_reward,
    terms,
    how_to_redeem,
    created_by_id,
    stat_views,
    stat_favorites,
    stat_clicks,
    stat_redemptions
) VALUES (
    'Brunch Domenicale €15',
    'brunch-domenicale-offerta',
    'Brunch all-inclusive ogni domenica. Dolce, salato, bevande calde e cocktail. Atmosfera rilassante con musica dal vivo.',
    'Brunch Domenica €15',
    'The Breakfast Club',
    'Via Solferino 25',
    'Milano',
    'MI',
    '20121',
    '+39 02 6664433',
    'info@breakfastclub.it',
    'ristoranti',
    ARRAY['brunch', 'colazione', 'domenica', 'buffet'],
    'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    'fixed',
    10.00,
    25.00,
    15.00,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    ARRAY['dom'],
    '10:00',
    '15:00',
    2,
    true,
    true,
    80,
    'Solo la domenica. Prenotazione obbligatoria.',
    'Prenota online e mostra il QR code all\'ingresso.',
    (SELECT id FROM users WHERE email = 'admin@cdm86.com'),
    450,
    38,
    225,
    29
);

-- Query di verifica
SELECT COUNT(*) as total_promotions FROM promotions;
